## torch.nn  / torch.nn.functional

### torch.nn.conv2d 와 torch.nn.functional.conv2d 차이점
- torch.nn.conv2d (in_channels, out_channels, kernel_size, stride ~~)
- torch.nn.functional.conv2d (input, weight, stride, ~~)  
즉, torch.nn은 weight를 입력하지 않아도 알아서 weight를 생성해 줌
  functoinal은 외부에서 만든 weight를 입력으로 넣어주어야 함

#### 1) nn.functoinal 

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [2]:
input = torch.ones(1,1,3,3)
filter = torch.ones(1,1,3,3)

In [4]:
input = Variable(input, requires_grad=True)
filter = Variable(filter)

In [5]:
out = F.conv2d(input=input, weight=filter)

print(out)

tensor([[[[9.]]]], grad_fn=<ThnnConv2DBackward>)


In [6]:
out.backward()

In [8]:
print(out.grad_fn)

In [9]:
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


#### 2) nn

In [11]:
input = torch.ones(1,1,3,3)
input = Variable(input, requires_grad=True)

In [12]:
func = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

In [13]:
func.weight

Parameter containing:
tensor([[[[-0.0865, -0.0597, -0.0771],
          [-0.1623, -0.2899, -0.0424],
          [ 0.0274,  0.3260, -0.3061]]]], requires_grad=True)

In [14]:
out = func(input)
out

tensor([[[[-0.5081]]]], grad_fn=<ThnnConv2DBackward>)

In [15]:
print(input.grad)

None


In [16]:
out.backward()

print(input.grad)

tensor([[[[-0.0865, -0.0597, -0.0771],
          [-0.1623, -0.2899, -0.0424],
          [ 0.0274,  0.3260, -0.3061]]]])


In [17]:
input = torch.ones(1, 1, 5,5)
input = Variable(input, requires_grad=True)

filter = nn.Conv2d(1, 1, 3, bias=None)

In [20]:
input,  filter.weight

(tensor([[[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]]], requires_grad=True), Parameter containing:
 tensor([[[[-0.0366,  0.2697,  0.3086],
           [-0.0872, -0.1257, -0.1522],
           [ 0.2564,  0.0812,  0.1406]]]], requires_grad=True))

- pretrained 모델과 같이 weight를 가져오거나 직접설정해서 하는 경우

In [23]:
filter.weight = torch.nn.Parameter(torch.ones(1,1,3,3) + 1)
filter.weight

Parameter containing:
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]], requires_grad=True)

In [24]:
out = filter(input)

In [25]:
print(out)

tensor([[[[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]], grad_fn=<ThnnConv2DBackward>)


### ReLU, sigmoid, tanh, Max Pooling

#### ReLU

In [26]:
act_input = Variable(torch.randn(1, 1, 3, 3))
print(act_input)

tensor([[[[-0.4976,  0.5158, -0.6658],
          [-0.5132,  1.2516,  0.2114],
          [ 1.7369,  0.4352, -1.2541]]]])


In [27]:
act = F.relu(act_input)
print(act)

tensor([[[[0.0000, 0.5158, 0.0000],
          [0.0000, 1.2516, 0.2114],
          [1.7369, 0.4352, 0.0000]]]])


#### sigmoid

In [28]:
act2 = F.sigmoid(act_input)
print(act2)

tensor([[[[0.3781, 0.6262, 0.3394],
          [0.3744, 0.7776, 0.5527],
          [0.8503, 0.6071, 0.2220]]]])


C:\Users\swoos\Anaconda3\lib\site-packages\torch\nn\functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


#### tanh

In [29]:
act3 = F.tanh(act_input)
print(act3)

tensor([[[[-0.4602,  0.4745, -0.5822],
          [-0.4724,  0.8487,  0.2084],
          [ 0.9399,  0.4097, -0.8494]]]])


C:\Users\swoos\Anaconda3\lib\site-packages\torch\nn\functional.py:1320: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


#### Pooling

In [30]:
m = nn.MaxPool2d(kernel_size=2, stride=1)
m_out = m(act)
print(m_out)

tensor([[[[1.2516, 1.2516],
          [1.7369, 1.2516]]]])


In [39]:
avg = nn.AvgPool2d(kernel_size=2, stride=1)
avg_out = avg(act3)
print(avg_out)

tensor([[[[0.0976, 0.2373],
          [0.4315, 0.1543]]]])
